<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
	<LangVersion>latest</LangVersion>
    <RootNamespace>BasePlugin_LabAPI</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Northwood.LabAPI" Version="1.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\Resources\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\Resources\Managed\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="CommandSystem.Core">
      <HintPath>..\Resources\Managed\CommandSystem.Core.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>..\Resources\Managed\Mirror.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\Resources\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
